# WezTerm wal color scheme
[colors]
foreground = "{foreground}"
background = "{background}"
cursor_bg = "{cursor}"
cursor_fg = "{background}"
cursor_border = "{cursor}"
selection_fg = "{background}"
selection_bg = "{cursor}"
scrollbar_thumb = "{color8}"
split = "{color8}"

ansi = [
  "{color0}",
  "{color1}",
  "{color2}",
  "{color3}",
  "{color4}",
  "{color5}",
  "{color6}",
  "{color7}",
]

brights = [
  "{color8}",
  "{color9}",
  "{color10}",
  "{color11}",
  "{color12}",
  "{color13}",
  "{color14}",
  "{color15}",
]